import React, { useState } from 'react';
import { Smartphone, CalendarPlus, QrCode, MessageCircle, CreditCard, Check } from 'lucide-react';
import { PLANS, calculateQuota, createPaymentOrder, activateSubscription, registerDevice, createEvent, createGallery, buildWhatsAppLink } from '../product.js';

const initialEvents=[{id:'evt-1',name:'Pernikahan Rani & Dimas',date:'2026-09-07',status:'live',createdAt:'2026-09-01T00:00:00Z'}];

export default function ProductDashboard({notify=()=>{}}){
 const [planId,setPlanId]=useState('pro'); const [subscription,setSubscription]=useState(null); const [order,setOrder]=useState(null);
 const [devices,setDevices]=useState([{id:'dev-1',name:'Kiosk-01',code:'PAIR01',status:'online'}]); const [deviceName,setDeviceName]=useState('');
 const [events,setEvents]=useState(initialEvents); const [eventName,setEventName]=useState(''); const [eventDate,setEventDate]=useState('');
 const [gallery,setGallery]=useState(createGallery(initialEvents[0],['rani-001.jpg','rani-002.jpg','rani-003.jpg'])); const [phone,setPhone]=useState(''); const [error,setError]=useState('');
 const usage={devices:devices.length,events:events.length,ai:746}; const quota=calculateQuota(planId,usage);
 function safe(fn){try{setError('');fn()}catch(e){setError(e.message)}}
 function choose(id){setPlanId(id);const next=createPaymentOrder(id,'loya-wedding');setOrder(next);notify(`Order ${next.id} dibuat`)}
 function pay(){safe(()=>{const next=activateSubscription(order);setSubscription(next);setOrder({...order,status:'paid'});notify(`Paket ${PLANS[next.planId].name} aktif`)})}
 function addDevice(e){e.preventDefault();safe(()=>{const device=registerDevice(devices,planId,deviceName);setDevices([...devices,device]);setDeviceName('');notify(`Kode pairing ${device.code}`)})}
 function addEvent(e){e.preventDefault();safe(()=>{const event=createEvent(events,planId,{name:eventName,date:eventDate});setEvents([event,...events]);setGallery(createGallery(event));setEventName('');setEventDate('');notify('Event berhasil dibuat')})}
 return <section className="page product-dashboard"><header><div><span className="eyebrow">BILLING & OPERASIONAL</span><h1>Kelola bisnis photobooth</h1><p>Langganan, perangkat, event, kuota, galeri QR, dan pengiriman WhatsApp dalam satu alur.</p></div>{subscription&&<span className="status"><i/> {PLANS[subscription.planId].name} aktif</span>}</header>
 {error&&<div className="alert" role="alert">{error}</div>}
 <div className="product-grid">
  <article className="panel span-2"><div className="panel-head"><h2><CreditCard/> Paket & pembayaran</h2><span className="pill">Provider manual/mock aktif</span></div><div className="compact-plans">{Object.values(PLANS).map(p=><button key={p.id} className={planId===p.id?'chosen':''} onClick={()=>choose(p.id)}><b>{p.name}</b><span>Rp{p.price.toLocaleString('id-ID')}</span><small>{p.billing==='monthly'?'per bulan':'sekali bayar'}</small></button>)}</div>{order&&<div className="checkout"><span>Order <b>{order.id}</b> · Rp{order.amount.toLocaleString('id-ID')}</span>{order.status==='pending'?<button className="primary" onClick={pay}>Simulasikan pembayaran</button>:<strong><Check/> Lunas & aktif</strong>}</div>}</article>
  <article className="panel"><h2><Smartphone/> Daftar perangkat</h2><form onSubmit={addDevice}><input aria-label="Nama perangkat" value={deviceName} onChange={e=>setDeviceName(e.target.value)} placeholder="Contoh: Kiosk Ballroom"/><button className="primary">Buat kode pairing</button></form><div className="item-list">{devices.map(d=><div key={d.id}><span><b>{d.name}</b><small>Kode: {d.code}</small></span><span className={'pill '+(d.status==='online'?'live':'')}>{d.status}</span></div>)}</div></article>
  <article className="panel"><h2><CalendarPlus/> Buat event</h2><form onSubmit={addEvent}><input aria-label="Nama event" value={eventName} onChange={e=>setEventName(e.target.value)} placeholder="Nama event"/><input aria-label="Tanggal event" type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)}/><button className="primary">Buat event</button></form><div className="item-list">{events.map(e=><div key={e.id}><span><b>{e.name}</b><small>{e.date}</small></span><span className="pill">{e.status}</span></div>)}</div></article>
  <article className="panel span-2"><h2>Penggunaan kuota — {PLANS[planId].name}</h2><div className="quota-grid">{Object.entries(quota).map(([key,q])=><div key={key}><span>{key==='ai'?'Generasi AI':key==='events'?'Event bulan ini':'Perangkat aktif'}</span><b>{q.used} / {q.limit??'∞'}</b><div className="bar"><i style={{width:q.limit?`${Math.min(100,q.used/q.limit*100)}%`:'0%'}}/></div><small>{q.remaining===null?'Tanpa batas':`${q.remaining} tersisa`}</small></div>)}</div><p className="quota-note">Event dan AI bulanan reset pada awal siklus langganan. Perangkat dihitung selama statusnya tidak dicabut. Pemrosesan ditolak tepat saat pemakaian mencapai batas.</p></article>
  <article className="panel gallery span-2"><div className="panel-head"><h2><QrCode/> Galeri QR & WhatsApp</h2><span className="pill live">Dipublikasikan</span></div><div className="gallery-flow"><div className="qr-box" aria-label="QR galeri"><QrCode/><small>{gallery.url}</small></div><div><h3>{gallery.eventName}</h3><p>{gallery.photos.length} foto siap dibagikan</p><div className="thumbs">{gallery.photos.map((p,i)=><span key={p}>Foto {i+1}</span>)}</div><div className="wa-row"><input aria-label="Nomor WhatsApp" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="0812 3456 7890"/><a className="primary" href={phone?buildWhatsAppLink(phone,gallery):'#'} target="_blank" rel="noreferrer" onClick={e=>{if(!phone){e.preventDefault();setError('Nomor WhatsApp wajib diisi')}}}><MessageCircle/> Kirim WhatsApp</a></div></div></div></article>
 </div>
 </section>
}
